# Generated by Django 5.1.4 on 2025-01-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "id_robot",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID del Robot"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del Robot"
                    ),
                ),
                ("equipo", models.CharField(max_length=100, verbose_name="Equipo")),
                (
                    "tipo_robot",
                    models.CharField(max_length=100, verbose_name="Tipo de Robot"),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Planificacion/",
                        verbose_name="Foto del Robot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre_usuario",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre de Usuario"
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="Contraseña"),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="Usuario Activo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncidenciaMantenimiento",
            fields=[
                (
                    "Id_incidencia",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID de la incidencia",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de la Incidencia"
                    ),
                ),
                (
                    "tipo_reparacion",
                    models.CharField(max_length=200, verbose_name="Tipo de Reparación"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "robot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidencias",
                        to="Planificacion.robot",
                        verbose_name="Robot Asociado",
                    ),
                ),
            ],
        ),
    ]
