# Generated by Django 5.1.4 on 2025-01-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Planificacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidenciamantenimiento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("sin_iniciar", "Sin Iniciar"),
                    ("en_proceso", "En Proceso"),
                    ("terminado", "Terminado"),
                ],
                default="sin_iniciar",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
