# Generated by Django 5.1.4 on 2025-01-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Planificacion", "0002_incidenciamantenimiento_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quejas",
            fields=[
                (
                    "id_queja",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID del Robot"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "apellido",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Apellido"
                    ),
                ),
                (
                    "cedula",
                    models.CharField(max_length=10, unique=True, verbose_name="Cédula"),
                ),
                (
                    "detalle",
                    models.CharField(
                        max_length=100, verbose_name="Detalle de la queja"
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        max_length=100, verbose_name="Correo Electronico"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="quejas/",
                        verbose_name="Foto del Robot",
                    ),
                ),
            ],
        ),
    ]
