# Generated by Django 5.1.4 on 2025-01-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Planificacion", "0003_quejas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quejas",
            name="apellido",
            field=models.CharField(max_length=100, verbose_name="Apellido"),
        ),
        migrations.AlterField(
            model_name="quejas",
            name="cedula",
            field=models.CharField(max_length=10, verbose_name="Cédula"),
        ),
        migrations.AlterField(
            model_name="quejas",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
    ]
