# Generated by Django 5.1.4 on 2025-02-06 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Planificacion", "0004_alter_quejas_apellido_alter_quejas_cedula_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id_actividad",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID de Actividad",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=255, verbose_name="Descripción de la Actividad"
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(verbose_name="Fecha de Inicio")),
                ("fecha_fin", models.DateTimeField(verbose_name="Fecha de Fin")),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id_cliente",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID de Cliente"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Cliente"),
                ),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "email",
                    models.EmailField(
                        max_length=100, verbose_name="Correo Electrónico"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="clientes/",
                        verbose_name="Foto del cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Constructora",
            fields=[
                (
                    "id_constructora",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID de Constructora",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de Constructora"
                    ),
                ),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "email",
                    models.EmailField(
                        max_length=100, verbose_name="Correo Electrónico"
                    ),
                ),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                (
                    "direccion",
                    models.CharField(max_length=255, verbose_name="Dirección"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vivienda",
            fields=[
                (
                    "id_vivienda",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID de Vivienda"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        max_length=255, verbose_name="Dirección de Vivienda"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Departamento", "Departamento"),
                            ("Casa", "Casa"),
                            ("Dúplex", "Dúplex"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Vivienda",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("En construcción", "En construcción"),
                            ("Terminada", "Terminada"),
                            ("Vendida", "Vendida"),
                        ],
                        max_length=50,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="viviendas/",
                        verbose_name="Foto de la Vivienda",
                    ),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viviendas",
                        to="Planificacion.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "id_constructora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Planificacion.constructora",
                        verbose_name="Constructora",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="incidenciamantenimiento",
            name="robot",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="actividad",
            name="id_constructora",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Planificacion.constructora",
                verbose_name="Constructora Asociada",
            ),
        ),
        migrations.AddField(
            model_name="actividad",
            name="id_vivienda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Planificacion.vivienda",
                verbose_name="Vivienda Asociada",
            ),
        ),
        migrations.DeleteModel(
            name="IncidenciaMantenimiento",
        ),
        migrations.DeleteModel(
            name="Robot",
        ),
    ]
